if(ANDROID OR CMAKE_SYSTEM_NAME STREQUAL "Android" OR DEFINED CMAKE_ANDROID_API OR DEFINED ANDROID_PLATFORM)
    set(VCPKG_TARGET_ANDROID true)
    set(FCT_ANDROID true)
else()
    set(VCPKG_TARGET_ANDROID false)
    set(FCT_ANDROID false)
endif()

if(WIN32)
    set(FCT_WIN32 true)
else()
    set(FCT_WIN32 false)
endif()